apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: operators
  namespace: argocd
spec:
  description: Project for my microservices managed via Argo CD
  sourceRepos:
    - 'https://github.com/rodkodanila/ocp-configs.git'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
