apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: worker-4x8
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: cilium-vwpvj
spec:
  replicas: 2
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: cilium-vwpvj
      machine.openshift.io/cluster-api-machineset: worker-4x8 
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: cilium-vwpvj
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: worker-4x8 
    spec:
      providerSpec:
        value:
          numCoresPerSocket: 4
          diskGiB: 50
          snapshot: ''
          userDataSecret:
            name: worker-user-data
          memoryMiB: 10000
          credentialsSecret:
            name: vsphere-cloud-credentials
          network:
            devices:
              - networkName: cilium
          metadata:
            creationTimestamp: null
          numCPUs: 4
          kind: VSphereMachineProviderSpec
          workspace:
            datacenter: dc1
            datastore: /dc1/datastore/ssd
            folder: /dc1/vm/cilium-vwpvj
            resourcePool: /dc1/host/ocp_cluster/Resources
            server: 192.168.8.170
          template: cilium-vwpvj-rhcos-generated-failure-domain
          apiVersion: machine.openshift.io/v1beta1
---
apiVersion: machine.openshift.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: worker-4x8
  namespace: openshift-machine-api
spec:
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-machine-role: worker
      machine.openshift.io/cluster-api-machine-type: worker
      machine.openshift.io/cluster-api-machineset: worker-4x8
  unhealthyConditions:
  - type: "Ready"
    timeout: "1200s"
    status: "False"
  - type: "Ready"
    timeout: "1200s"
    status: "Unknown"
  maxUnhealthy: "1"
