apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: vault-secrets-operator
  namespace: devsecops-vault-secret-operator
spec:
  channel: stable
  installPlanApproval: Manual
  name: vault-secrets-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: vault-secrets-operator.v1.2.0