apiVersion: route.openshift.io/v1
kind: Route
metadata:
  namespace: openshift-console
  name: console-system
  labels: 
    app.kubernetes.io/instance: system-router
spec:
  host: console-openshift-console.system.redcluster.danila.home
  port:
    targetPort: https
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt
  to:
    kind: Service
    name: console
    weight: 100
  wildcardPolicy: None