apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-vcenter-api-access
  namespace: openshift-cluster-storage-operator
spec:
  podSelector: {}  # Applies to ALL pods in this namespace
  policyTypes:
  - Egress
  egress:
  # Rule 1: Allow HTTPS to the specific external IP
  - to:
    - ipBlock:
        cidr: 19.168.8.170/32
    ports:
    - protocol: TCP
      port: 443