apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-access-to-vsphere-api"
  namespace: "openshift-cluster-storage-operator"
spec:
  endpointSelector:
    matchLabels: {}
  egress:
  - toCIDR:
    - "192.168.8.170/32"
    toPorts:
    - ports:
      - port: "443"
        protocol: TCP