apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-networkpolicy-role
  namespace: openshift-cloud-credential-operator
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-networkpolicy-binding
  namespace: openshift-cloud-credential-operator
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-networkpolicy-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-networkpolicy-role
  namespace: openshift-cluster-storage-operator
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-networkpolicy-binding
  namespace: openshift-cluster-storage-operator 
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-networkpolicy-role