apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-operator
  namespace: openshift-gitops 
spec:
  project: operators 
  source:
    repoURL: 'https://github.com/rodkodanila/ocp-configs.git'
    targetRevision: main
    path: metallb-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
