apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vso-operator
  namespace: openshift-gitops 
spec:
  project: operators 
  source:
    repoURL: 'https://github.com/rodkodanila/ocp-configs.git'
    targetRevision: main
    path: vault-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: devsecops-vault-secret-operator
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
