apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-for-apps
  namespace: openshift-gitops 
spec:
  project: default 
  source:
    repoURL: 'https://github.com/rodkodanila/ocp-configs.git'
    targetRevision: main
    path: openshift-cluster/cluster-sec/argocd/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops 
  syncPolicy:
    automated:
      prune: false 
      selfHeal: true