apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: openshift-gitops 
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/rodkodanila/ocp-configs.git'
      targetRevision: main
      path: argocd/applications
    - repoURL: 'https://github.com/rodkodanila/ocp-configs.git'
      targetRevision: main
      path: argocd/projects
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
